
[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/patterns/echo"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/echo/foxtrot"
  to = "/.netlify/functions/foxtrot/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/echo/:splat"
  status = 200

